### PR TITLE
 arpspoof as module. pep8

### PR DESCRIPTION
**Pull request by llazzaro**
arpspoof is now a python module:
- this allows the project to be published in pypi
- will install dependencies
- add console command "arpspoof"

some PEP8 fixes in the code (remove import *, replaced tabs by spaces,etc)

### CODE REVIEW

**Comment by byt3bl33d3r** [comment]
@llazzaro dude! this is awesome! thanks a bunch! 
I'm not really familiar with module packaging, but looking at the files it seems that it implies `arpspoof` would be compatible with Python 3 (which it isn't)
Is there a way of specifying this anywhere ?

Thanks again!

**Comment by llazzaro** [comment]
done! removed python 3 classifiers.

**Comment by byt3bl33d3r** [comment]
@llazzaro perfect! thanks again! merged!

**Comment by llazzaro** [comment]
if you want arpspoof can be published at pipy:
http://peterdowns.com/posts/first-time-with-pypi.html

**Pull request merged**
